name: build-and-push-ecr

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - requirements.txt
      - 'requirements*.txt'
      - 'pyproject.toml'
      - 'poetry.lock'
      - src/**
      - app/**
      - config/**
      - scripts/**
      - .github/workflows/build-and-push-ecr.yml

permissions:
  id-token: write
  contents: read

concurrency:
  group: build-and-push-ecr-${{ github.ref }}
  cancel-in-progress: false

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: '969932165253'
  ECR_REPO: quant-bot-app
  IMAGE_URI: 969932165253.dkr.ecr.us-east-1.amazonaws.com/quant-bot-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_IAM_ROLE_ARN: ${{ secrets.AWS_IAM_ROLE_ARN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        if: ${{ env.AWS_IAM_ROLE_ARN != '' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure AWS credentials (access keys)
        if: ${{ env.AWS_IAM_ROLE_ARN == '' && env.AWS_ACCESS_KEY_ID != '' && env.AWS_SECRET_ACCESS_KEY != '' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Fail if no AWS credentials provided
        if: ${{ env.AWS_IAM_ROLE_ARN == '' && (env.AWS_ACCESS_KEY_ID == '' || env.AWS_SECRET_ACCESS_KEY == '') }}
        run: |
          echo "No AWS credentials available. Set AWS_IAM_ROLE_ARN for OIDC or AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY for classic keys." >&2
          exit 1

      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set tags
        id: vars
        run: |
          echo "sha_tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
          echo "latest_tag=latest" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_URI }}:${{ steps.vars.outputs.sha_tag }}
            ${{ env.IMAGE_URI }}:${{ steps.vars.outputs.latest_tag }}
          provenance: false

      - name: Output image URIs
        run: |
          echo "Pushed:"
          echo " - ${{ env.IMAGE_URI }}:${{ steps.vars.outputs.sha_tag }}"
          if [ "${GITHUB_REF}" = "refs/heads/main" ]; then
            echo " - ${{ env.IMAGE_URI }}:${{ steps.vars.outputs.latest_tag }}"
          fi
